// Code generated by 'go generate'; DO NOT EDIT.

package windriver

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modgdi32    = windows.NewLazySystemDLL("gdi32.dll")
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")
	modshell32  = windows.NewLazySystemDLL("shell32.dll")
	moduser32   = windows.NewLazySystemDLL("user32.dll")

	procBitBlt                   = modgdi32.NewProc("BitBlt")
	procCreateBitmap             = modgdi32.NewProc("CreateBitmap")
	procCreateBitmapIndirect     = modgdi32.NewProc("CreateBitmapIndirect")
	procCreateCompatibleBitmap   = modgdi32.NewProc("CreateCompatibleBitmap")
	procCreateCompatibleDC       = modgdi32.NewProc("CreateCompatibleDC")
	procCreateDIBSection         = modgdi32.NewProc("CreateDIBSection")
	procDeleteDC                 = modgdi32.NewProc("DeleteDC")
	procDeleteObject             = modgdi32.NewProc("DeleteObject")
	procGetObject                = modgdi32.NewProc("GetObject")
	procSelectObject             = modgdi32.NewProc("SelectObject")
	procSetPixel                 = modgdi32.NewProc("SetPixel")
	procGetConsoleWindow         = modkernel32.NewProc("GetConsoleWindow")
	procGetCurrentProcessId      = modkernel32.NewProc("GetCurrentProcessId")
	procGetModuleHandleW         = modkernel32.NewProc("GetModuleHandleW")
	procGlobalAlloc              = modkernel32.NewProc("GlobalAlloc")
	procGlobalLock               = modkernel32.NewProc("GlobalLock")
	procGlobalUnlock             = modkernel32.NewProc("GlobalUnlock")
	procDragAcceptFiles          = modshell32.NewProc("DragAcceptFiles")
	procDragFinish               = modshell32.NewProc("DragFinish")
	procDragQueryFileW           = modshell32.NewProc("DragQueryFileW")
	procDragQueryPoint           = modshell32.NewProc("DragQueryPoint")
	procBeginPaint               = moduser32.NewProc("BeginPaint")
	procClientToScreen           = moduser32.NewProc("ClientToScreen")
	procCloseClipboard           = moduser32.NewProc("CloseClipboard")
	procCreateWindowExW          = moduser32.NewProc("CreateWindowExW")
	procDefWindowProcW           = moduser32.NewProc("DefWindowProcW")
	procDestroyWindow            = moduser32.NewProc("DestroyWindow")
	procDispatchMessageW         = moduser32.NewProc("DispatchMessageW")
	procEmptyClipboard           = moduser32.NewProc("EmptyClipboard")
	procEndPaint                 = moduser32.NewProc("EndPaint")
	procGetClipboardData         = moduser32.NewProc("GetClipboardData")
	procGetCursorPos             = moduser32.NewProc("GetCursorPos")
	procGetDC                    = moduser32.NewProc("GetDC")
	procGetKeyState              = moduser32.NewProc("GetKeyState")
	procGetKeyboardState         = moduser32.NewProc("GetKeyboardState")
	procGetMessageW              = moduser32.NewProc("GetMessageW")
	procGetWindowRect            = moduser32.NewProc("GetWindowRect")
	procGetWindowThreadProcessId = moduser32.NewProc("GetWindowThreadProcessId")
	procInvalidateRect           = moduser32.NewProc("InvalidateRect")
	procLoadCursorW              = moduser32.NewProc("LoadCursorW")
	procLoadImageW               = moduser32.NewProc("LoadImageW")
	procMapVirtualKeyW           = moduser32.NewProc("MapVirtualKeyW")
	procMapWindowPoints          = moduser32.NewProc("MapWindowPoints")
	procOpenClipboard            = moduser32.NewProc("OpenClipboard")
	procPostMessageW             = moduser32.NewProc("PostMessageW")
	procPostQuitMessage          = moduser32.NewProc("PostQuitMessage")
	procRedrawWindow             = moduser32.NewProc("RedrawWindow")
	procRegisterClassExW         = moduser32.NewProc("RegisterClassExW")
	procReleaseDC                = moduser32.NewProc("ReleaseDC")
	procSetClipboardData         = moduser32.NewProc("SetClipboardData")
	procSetCursor                = moduser32.NewProc("SetCursor")
	procSetCursorPos             = moduser32.NewProc("SetCursorPos")
	procSetWindowTextW           = moduser32.NewProc("SetWindowTextW")
	procShowWindow               = moduser32.NewProc("ShowWindow")
	procShowWindowAsync          = moduser32.NewProc("ShowWindowAsync")
	procToUnicode                = moduser32.NewProc("ToUnicode")
	procTranslateAccelerator     = moduser32.NewProc("TranslateAccelerator")
	procTranslateMessage         = moduser32.NewProc("TranslateMessage")
	procUpdateWindow             = moduser32.NewProc("UpdateWindow")
	procValidateRect             = moduser32.NewProc("ValidateRect")
)

func _BitBlt(hdc windows.Handle, x int32, y int32, w int32, h int32, hdcSrc windows.Handle, x2 int32, y2 int32, rOp uint32) (ok bool) {
	r0, _, _ := syscall.SyscallN(procBitBlt.Addr(), uintptr(hdc), uintptr(x), uintptr(y), uintptr(w), uintptr(h), uintptr(hdcSrc), uintptr(x2), uintptr(y2), uintptr(rOp))
	ok = r0 != 0
	return
}

func _CreateBitmap(w int32, h int32, planes uint32, bitCount uint32, bits uintptr) (bmH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateBitmap.Addr(), uintptr(w), uintptr(h), uintptr(planes), uintptr(bitCount), uintptr(bits))
	bmH = windows.Handle(r0)
	if bmH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _CreateBitmapIndirect(bm *_Bitmap) (bmH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateBitmapIndirect.Addr(), uintptr(unsafe.Pointer(bm)))
	bmH = windows.Handle(r0)
	if bmH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _CreateCompatibleBitmap(hdc windows.Handle, w int32, h int32) (bmH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateCompatibleBitmap.Addr(), uintptr(hdc), uintptr(w), uintptr(h))
	bmH = windows.Handle(r0)
	if bmH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _CreateCompatibleDC(hdc windows.Handle) (dcH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateCompatibleDC.Addr(), uintptr(hdc))
	dcH = windows.Handle(r0)
	if dcH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _CreateDIBSection(dc windows.Handle, bmi *_BitmapInfo, usage uint32, bits **byte, section windows.Handle, offset uint32) (bmH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateDIBSection.Addr(), uintptr(dc), uintptr(unsafe.Pointer(bmi)), uintptr(usage), uintptr(unsafe.Pointer(bits)), uintptr(section), uintptr(offset))
	bmH = windows.Handle(r0)
	if bmH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _DeleteDC(dc windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procDeleteDC.Addr(), uintptr(dc))
	ok = r0 != 0
	return
}

func _DeleteObject(obj windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procDeleteObject.Addr(), uintptr(obj))
	ok = r0 != 0
	return
}

func _GetObject(h windows.Handle, c int32, v uintptr) (n int) {
	r0, _, _ := syscall.SyscallN(procGetObject.Addr(), uintptr(h), uintptr(c), uintptr(v))
	n = int(r0)
	return
}

func _SelectObject(hdc windows.Handle, obj windows.Handle) (prevObjH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procSelectObject.Addr(), uintptr(hdc), uintptr(obj))
	prevObjH = windows.Handle(r0)
	if prevObjH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _SetPixel(hdc windows.Handle, x int, y int, c _ColorRef) (colorSet int32, err error) {
	r0, _, e1 := syscall.SyscallN(procSetPixel.Addr(), uintptr(hdc), uintptr(x), uintptr(y), uintptr(c))
	colorSet = int32(r0)
	if colorSet == -1 {
		err = errnoErr(e1)
	}
	return
}

func _GetConsoleWindow() (cH windows.Handle) {
	r0, _, _ := syscall.SyscallN(procGetConsoleWindow.Addr())
	cH = windows.Handle(r0)
	return
}

func _GetCurrentProcessId() (pid uint32) {
	r0, _, _ := syscall.SyscallN(procGetCurrentProcessId.Addr())
	pid = uint32(r0)
	return
}

func _GetModuleHandleW(name *uint16) (modH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procGetModuleHandleW.Addr(), uintptr(unsafe.Pointer(name)))
	modH = windows.Handle(r0)
	if modH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _GlobalAlloc(uFlags uint32, dwBytes uintptr) (h windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procGlobalAlloc.Addr(), uintptr(uFlags), uintptr(dwBytes))
	h = windows.Handle(r0)
	if h == 0 {
		err = errnoErr(e1)
	}
	return
}

func _GlobalLock(h windows.Handle) (ptr uintptr, err error) {
	r0, _, e1 := syscall.SyscallN(procGlobalLock.Addr(), uintptr(h))
	ptr = uintptr(r0)
	if ptr == 0 {
		err = errnoErr(e1)
	}
	return
}

func _GlobalUnlock(h windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procGlobalUnlock.Addr(), uintptr(h))
	ok = r0 != 0
	return
}

func _DragAcceptFiles(hwnd windows.Handle, fAccept bool) {
	var _p0 uint32
	if fAccept {
		_p0 = 1
	}
	syscall.SyscallN(procDragAcceptFiles.Addr(), uintptr(hwnd), uintptr(_p0))
	return
}

func _DragFinish(hDrop uintptr) {
	syscall.SyscallN(procDragFinish.Addr(), uintptr(hDrop))
	return
}

func _DragQueryFileW(hDrop uintptr, iFile uint32, lpszFile *uint16, cch uint32) (res uint32) {
	r0, _, _ := syscall.SyscallN(procDragQueryFileW.Addr(), uintptr(hDrop), uintptr(iFile), uintptr(unsafe.Pointer(lpszFile)), uintptr(cch))
	res = uint32(r0)
	return
}

func _DragQueryPoint(hDrop uintptr, ppt *_Point) (res bool) {
	r0, _, _ := syscall.SyscallN(procDragQueryPoint.Addr(), uintptr(hDrop), uintptr(unsafe.Pointer(ppt)))
	res = r0 != 0
	return
}

func _BeginPaint(hwnd windows.Handle, paint *_Paint) (dcH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procBeginPaint.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(paint)))
	dcH = windows.Handle(r0)
	if dcH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _ClientToScreen(hwnd windows.Handle, lpPoint *_Point) (ok bool) {
	r0, _, _ := syscall.SyscallN(procClientToScreen.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(lpPoint)))
	ok = r0 != 0
	return
}

func _CloseClipboard() (ok bool) {
	r0, _, _ := syscall.SyscallN(procCloseClipboard.Addr())
	ok = r0 != 0
	return
}

func _CreateWindowExW(dwExStyle uint32, lpClassName *uint16, lpWindowName *uint16, dwStyle int32, x int32, y int32, nWidth int32, nHeight int32, hWndParent windows.Handle, hMenu windows.Handle, hInstance windows.Handle, lpParam uintptr) (wndH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateWindowExW.Addr(), uintptr(dwExStyle), uintptr(unsafe.Pointer(lpClassName)), uintptr(unsafe.Pointer(lpWindowName)), uintptr(dwStyle), uintptr(x), uintptr(y), uintptr(nWidth), uintptr(nHeight), uintptr(hWndParent), uintptr(hMenu), uintptr(hInstance), uintptr(lpParam))
	wndH = windows.Handle(r0)
	if wndH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _DefWindowProcW(hwnd windows.Handle, msg uint32, wparam uintptr, lparam uintptr) (ret uintptr) {
	r0, _, _ := syscall.SyscallN(procDefWindowProcW.Addr(), uintptr(hwnd), uintptr(msg), uintptr(wparam), uintptr(lparam))
	ret = uintptr(r0)
	return
}

func _DestroyWindow(hwnd windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procDestroyWindow.Addr(), uintptr(hwnd))
	ok = r0 != 0
	return
}

func _DispatchMessageW(msg *_Msg) (res int32) {
	r0, _, _ := syscall.SyscallN(procDispatchMessageW.Addr(), uintptr(unsafe.Pointer(msg)))
	res = int32(r0)
	return
}

func _EmptyClipboard() (ok bool) {
	r0, _, _ := syscall.SyscallN(procEmptyClipboard.Addr())
	ok = r0 != 0
	return
}

func _EndPaint(hwnd windows.Handle, paint *_Paint) (ok bool) {
	r0, _, _ := syscall.SyscallN(procEndPaint.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(paint)))
	ok = r0 != 0
	return
}

func _GetClipboardData(uFormat uint32) (dataH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procGetClipboardData.Addr(), uintptr(uFormat))
	dataH = windows.Handle(r0)
	if dataH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _GetCursorPos(p *_Point) (ok bool) {
	r0, _, _ := syscall.SyscallN(procGetCursorPos.Addr(), uintptr(unsafe.Pointer(p)))
	ok = r0 != 0
	return
}

func _GetDC(hwnd windows.Handle) (dcH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procGetDC.Addr(), uintptr(hwnd))
	dcH = windows.Handle(r0)
	if dcH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _GetKeyState(vkey int32) (state uint16) {
	r0, _, _ := syscall.SyscallN(procGetKeyState.Addr(), uintptr(vkey))
	state = uint16(r0)
	return
}

func _GetKeyboardState(state *[256]byte) (ok bool) {
	r0, _, _ := syscall.SyscallN(procGetKeyboardState.Addr(), uintptr(unsafe.Pointer(state)))
	ok = r0 != 0
	return
}

func _GetMessageW(msg *_Msg, hwnd windows.Handle, msgFilterMin uint32, msgFilterMax uint32) (res int32, err error) {
	r0, _, e1 := syscall.SyscallN(procGetMessageW.Addr(), uintptr(unsafe.Pointer(msg)), uintptr(hwnd), uintptr(msgFilterMin), uintptr(msgFilterMax))
	res = int32(r0)
	if res == -1 {
		err = errnoErr(e1)
	}
	return
}

func _GetWindowRect(hwnd windows.Handle, r *_Rect) (ok bool) {
	r0, _, _ := syscall.SyscallN(procGetWindowRect.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(r)))
	ok = r0 != 0
	return
}

func _GetWindowThreadProcessId(hwnd windows.Handle, pid *uint32) (threadId uint32) {
	r0, _, _ := syscall.SyscallN(procGetWindowThreadProcessId.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(pid)))
	threadId = uint32(r0)
	return
}

func _InvalidateRect(hwnd windows.Handle, r *_Rect, erase bool) (ok bool) {
	var _p0 uint32
	if erase {
		_p0 = 1
	}
	r0, _, _ := syscall.SyscallN(procInvalidateRect.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(r)), uintptr(_p0))
	ok = r0 != 0
	return
}

func _LoadCursorW(hInstance windows.Handle, name uint32) (cursorH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procLoadCursorW.Addr(), uintptr(hInstance), uintptr(name))
	cursorH = windows.Handle(r0)
	if cursorH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _LoadImageW(hInstance windows.Handle, name uintptr, typ uint32, cx int32, cy int32, fuLoad uint32) (imgH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procLoadImageW.Addr(), uintptr(hInstance), uintptr(name), uintptr(typ), uintptr(cx), uintptr(cy), uintptr(fuLoad))
	imgH = windows.Handle(r0)
	if imgH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _MapVirtualKeyW(uCode uint32, uMapType uint32) (code uint32) {
	r0, _, _ := syscall.SyscallN(procMapVirtualKeyW.Addr(), uintptr(uCode), uintptr(uMapType))
	code = uint32(r0)
	return
}

func _MapWindowPoints(hwndFrom windows.Handle, hwndTo windows.Handle, lpPoints *_Point, cPoints uint32) (res int32) {
	r0, _, _ := syscall.SyscallN(procMapWindowPoints.Addr(), uintptr(hwndFrom), uintptr(hwndTo), uintptr(unsafe.Pointer(lpPoints)), uintptr(cPoints))
	res = int32(r0)
	return
}

func _OpenClipboard(hWndNewOwner windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procOpenClipboard.Addr(), uintptr(hWndNewOwner))
	ok = r0 != 0
	return
}

func _PostMessageW(hwnd windows.Handle, msg uint32, wParam uintptr, lParam uintptr) (ok bool) {
	r0, _, _ := syscall.SyscallN(procPostMessageW.Addr(), uintptr(hwnd), uintptr(msg), uintptr(wParam), uintptr(lParam))
	ok = r0 != 0
	return
}

func _PostQuitMessage(exitCode int32) {
	syscall.SyscallN(procPostQuitMessage.Addr(), uintptr(exitCode))
	return
}

func _RedrawWindow(hwnd windows.Handle, r *_Rect, region windows.Handle, flags uint) (ok bool) {
	r0, _, _ := syscall.SyscallN(procRedrawWindow.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(r)), uintptr(region), uintptr(flags))
	ok = r0 != 0
	return
}

func _RegisterClassExW(wcx *_WndClassExW) (atom uint16, err error) {
	r0, _, e1 := syscall.SyscallN(procRegisterClassExW.Addr(), uintptr(unsafe.Pointer(wcx)))
	atom = uint16(r0)
	if atom == 0 {
		err = errnoErr(e1)
	}
	return
}

func _ReleaseDC(hwnd windows.Handle, dc windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procReleaseDC.Addr(), uintptr(hwnd), uintptr(dc))
	ok = r0 != 0
	return
}

func _SetClipboardData(uFormat uint32, h windows.Handle) (dataH windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procSetClipboardData.Addr(), uintptr(uFormat), uintptr(h))
	dataH = windows.Handle(r0)
	if dataH == 0 {
		err = errnoErr(e1)
	}
	return
}

func _SetCursor(cursorH windows.Handle) (prevCursorH windows.Handle) {
	r0, _, _ := syscall.SyscallN(procSetCursor.Addr(), uintptr(cursorH))
	prevCursorH = windows.Handle(r0)
	return
}

func _SetCursorPos(x int32, y int32) (ok bool) {
	r0, _, _ := syscall.SyscallN(procSetCursorPos.Addr(), uintptr(x), uintptr(y))
	ok = r0 != 0
	return
}

func _SetWindowTextW(hwnd windows.Handle, lpString *uint16) (res bool) {
	r0, _, _ := syscall.SyscallN(procSetWindowTextW.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(lpString)))
	res = r0 != 0
	return
}

func _ShowWindow(hwnd windows.Handle, nCmdShow int) (ok bool) {
	r0, _, _ := syscall.SyscallN(procShowWindow.Addr(), uintptr(hwnd), uintptr(nCmdShow))
	ok = r0 != 0
	return
}

func _ShowWindowAsync(hwnd windows.Handle, nCmdShow int) (ok bool) {
	r0, _, _ := syscall.SyscallN(procShowWindowAsync.Addr(), uintptr(hwnd), uintptr(nCmdShow))
	ok = r0 != 0
	return
}

func _ToUnicode(wVirtKey uint32, wScanCode uint32, lpKeyState *[256]byte, pwszBuff *uint16, cchBuff int32, wFlags uint32) (code int32) {
	r0, _, _ := syscall.SyscallN(procToUnicode.Addr(), uintptr(wVirtKey), uintptr(wScanCode), uintptr(unsafe.Pointer(lpKeyState)), uintptr(unsafe.Pointer(pwszBuff)), uintptr(cchBuff), uintptr(wFlags))
	code = int32(r0)
	return
}

func _TranslateAccelerator(hwnd windows.Handle, hAccTable windows.Handle, msg *_Msg) (ok bool) {
	r0, _, _ := syscall.SyscallN(procTranslateAccelerator.Addr(), uintptr(hwnd), uintptr(hAccTable), uintptr(unsafe.Pointer(msg)))
	ok = r0 != 0
	return
}

func _TranslateMessage(msg *_Msg) (translated bool) {
	r0, _, _ := syscall.SyscallN(procTranslateMessage.Addr(), uintptr(unsafe.Pointer(msg)))
	translated = r0 != 0
	return
}

func _UpdateWindow(hwnd windows.Handle) (ok bool) {
	r0, _, _ := syscall.SyscallN(procUpdateWindow.Addr(), uintptr(hwnd))
	ok = r0 != 0
	return
}

func _ValidateRect(hwnd windows.Handle, r *_Rect) (ok bool) {
	r0, _, _ := syscall.SyscallN(procValidateRect.Addr(), uintptr(hwnd), uintptr(unsafe.Pointer(r)))
	ok = r0 != 0
	return
}
